Translate the document to English
Ink-33/OhMyStream9 pull request #3
Opened 2022-09-01 06:58 UTC by NoNormalCreeper

I don't know if I should add my name in the *license* section, so I'm not adding it yet.

2022-09-02 17:48 UTC, Ink-33 requested changes

2022-09-02 17:48 UTC, Ink-33 commented on README_EN.md
> +Listen, dude! Did you know? In December 31st, 2021, `CentOS 8` ~~was finished! 🎉🎉🎉~~
``` markdown
It was December 31st, 2021 that `CentOS 8` reached end of life!  🎉🎉🎉  
```
Please note the two spaces at the end of the sentence.

2022-09-02 17:48 UTC, Ink-33 commented on README_EN.md
> +Unfortunately my VPS provider doesn't provide `CentOS Stream 9` image, or even `CentOS Stream 8` image, so I have to use the outdated `CentOS 8` image, isn't that bad?
But my VPS provider doesn't provide a `CentOS Stream 9` image, or even a `CentOS Stream 8` image, so I have to use an outdated `CentOS 8` image, wouldn't that be bad?

2022-09-02 17:48 UTC, Ink-33 commented on README_EN.md
> +Don't worry, with the method provided in this article, you can also upgrade to `CentOS Stream 9` on `CentOS 8`, with all your data kept and no need to reinstall system!
Don't worry, with the method provided in this article, you can also upgrade to `CentOS Stream 9` from `CentOS 8`, with all your data kept and not have to reinstall your system!

2022-09-02 17:48 UTC, Ink-33 commented on README_EN.md
> +**WARNING**: Upgrading a large version may cause the software or even the system to not work properly, so please be careful!
Upgrading a major version may cause the software or even the system to fail to operate properly, so please be careful!

2022-09-02 17:48 UTC, Ink-33 commented on README_EN.md
> +**TIPS**: Please read the whole article before you start the operation. If you encounter a problem, you can open an `issue` and create a `pull request` for a better solution.
Fell free to open an `issue` when you encounter a problem. If you would like to share a better solution, please submit a `pull request` to help us improve the documention.

2022-09-02 17:48 UTC, Ink-33 commented on README.md
Please help me change L9 to 
``` markdown 
哦，我的老伙计！你知道吗？`CentOS 8`在2021年12月31日完蛋啦！🎉🎉🎉  
```
Please note the two spaces at the end of the sentence.

2022-09-04 13:24 UTC, NoNormalCreeper commented
Modified.

2022-09-04 15:50 UTC, Ink-33 approved these changes

2022-09-04 15:51 UTC, merged